SET SERVEROUTPUT ON;
DECLARE 
   a number(4);
BEGIN 
   FOR a in 1 .. 50 LOOP 
       INSERT INTO USUARIO (CODIGO, NOMBRE_USUARIO, FK_GENERO, SIGO_VIRGO, FACHA, EDAD) 
       VALUES (a, 'Usuario'||TO_CHAR(a), 'MASCULINO', 'S', 'S', (70-a));
    
       INSERT INTO USUARIO_VERSION (FK_USUARIO, FK_VERSION) 
                    VALUES (a, 'V4');
       INSERT INTO USUARIO_VERSION (FK_USUARIO, FK_VERSION) 
                    VALUES (a, 'V5');
       INSERT INTO USUARIO_VERSION (FK_USUARIO, FK_VERSION) 
                    VALUES (a, 'V6');
  END LOOP; 
END; 
/






CREATE TABLE "TARINGA"."GENERO" 
   (	"TIPO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "GENERO_PK" PRIMARY KEY ("TIPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  
CREATE TABLE "TARINGA"."USUARIO" 
   (	"CODIGO" NUMBER(35,0) NOT NULL ENABLE, 
	"NOMBRE_USUARIO" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"FK_GENERO" VARCHAR2(50 BYTE), 
	"SIGO_VIRGO" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"FACHA" VARCHAR2(1 BYTE), 
	"EDAD" NUMBER(3,0), 
	 CONSTRAINT "USUARIO_PK" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "USUARIO_FK1" FOREIGN KEY ("FK_GENERO")
	  REFERENCES "TARINGA"."GENERO" ("TIPO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  
CREATE TABLE "TARINGA"."USUARIO_VERSION" 
   (	"FK_USUARIO" NUMBER(35,0) NOT NULL ENABLE, 
	"FK_VERSION" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "USUARIO_VERSION_PK" PRIMARY KEY ("FK_USUARIO", "FK_VERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "USUARIO_VERSION_FK1" FOREIGN KEY ("FK_VERSION")
	  REFERENCES "TARINGA"."VERSION" ("CODIGO") ENABLE, 
	 CONSTRAINT "USUARIO_VERSION_FK2" FOREIGN KEY ("FK_USUARIO")
	  REFERENCES "TARINGA"."USUARIO" ("CODIGO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

 CREATE TABLE "TARINGA"."VERSION" 
   (	"CODIGO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(50 BYTE), 
	 CONSTRAINT "VERSION_PK" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  